<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Formulir Pendaftaran Iuran</title>
    <style>
        body { font-family: Arial, sans-serif; padding: 20px; background: #f5f5f5; }
        .container { background: white; padding: 20px; border-radius: 10px; max-width: 600px; margin: auto; box-shadow: 0 0 10px rgba(0,0,0,0.1); }
        h2 { text-align: center; color: #4CAF50; }
        label { display: block; margin-top: 15px; }
        input, select, textarea { width: 100%; padding: 8px; margin-top: 5px; border: 1px solid #ccc; border-radius: 5px; }
        button { margin-top: 20px; background: #4CAF50; color: white; padding: 10px; border: none; border-radius: 5px; cursor: pointer; width: 100%; }
        button:hover { background: #45a049; }
    </style>
</head>
<body>
    <div class="container">
        <h2>Formulir Pendaftaran Iuran</h2>
        <form id="iuranForm">
            <label>Nama (姓名)</label>
            <input type="text" name="nama" required>

            <label>Alamat (地址)</label>
            <textarea name="alamat" required></textarea>

            <label>Masa Iuran (月捐期限)</label>
            <select name="masaIuran" required>
                <option value="">-- Pilih Masa Iuran --</option>
                <option>April 2024 - Maret 2025</option>
                <option>April 2025 - Maret 2026</option>
                <option>April 2026 - Maret 2027</option>
                <option>April 2027 - Maret 2028</option>
                <option>April 2028 - Maret 2029</option>
                <option>April 2029 - Maret 2030</option>
                <option>April 2030 - Maret 2031</option>
                <option>April 2031 - Maret 2032</option>
                <option>April 2032 - Maret 2033</option>
                <option>April 2033 - Maret 2034</option>
                <option>April 2034 - Maret 2035</option>
            </select>

            <label>Jumlah Iuran per Bulan (Rp) (每月月捐)</label>
            <input type="number" name="jumlahIuran" required>

            <label>No HP/WA</label>
            <input type="text" name="nohp" required>

            <label>Tanggal Pengisian (日期)</label>
            <input type="date" name="tanggal" required>

            <label>Tanda Tangan Bendahara (Nama)</label>
            <input type="text" name="ttdBendahara">

            <label>Tanda Tangan Ketua (Nama)</label>
            <input type="text" name="ttdKetua">

            <button type="submit">Kirim</button>
        </form>
        <div id="notif" style="margin-top:20px; color:green;"></div>
    </div>

    <script>
    document.getElementById('iuranForm').addEventListener('submit', function(e) {
        e.preventDefault();
        
        const formData = new FormData(this);
        const data = {};

        formData.forEach((value, key) => data[key] = value);

        fetch('PASTE_URL_WEB_APP_KAMU', {
            method: 'POST',
            mode: 'no-cors',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        }).then(response => {
            document.getElementById('notif').innerText = "Formulir berhasil dikirim! Terima kasih.";
            document.getElementById('iuranForm').reset();
        }).catch(error => {
            document.getElementById('notif').innerText = "Gagal mengirim formulir.";
        });
    });
    </script>
</body>
</html>
    
